server:
  port: 10086
spring:
  application:
    name: ly--registry
  devtools:
    restart:
      enabled: true  #设置开启热部署
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
    register-with-eureka: false
    fetch-registry: false