server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  devtools:
    restart:
      enabled: true  #设置开启热部署
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.153.129:22122
ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/png
      - image/bmp
      - image/jpeg