server:
  port: 8086
spring:
  application:
    name: sms-service
  devtools:
    restart:
      enabled: true  #设置开启热部署
  rabbitmq:
    host: 192.168.153.129
    username: guest
    password: guest
  redis:
    #数据库索引
      host: 192.168.153.129
      port: 6379
ly:
  sms:
    accessKeyId: LTAIxjqRJoeyf4kO # 自己的accessKeyId
    accessKeySecret: vYGT3XzfuSKgq2klSzTTnOu87CDenr # 自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_164575105 # 模板名称 sms参数均少一位，ID密码去阿里云官方申请