#server:
  #port: 8083
spring:
  application:
    name: search-service
  devtools:
    restart:
      enabled: true  #设置开启热部署
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.153.129:9300
  jackson:
    default-property-inclusion: non_null #排除返回结构中字段值为null的属性
  rabbitmq:
    host: 192.168.153.129
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      registry-fetch-interval-seconds: 10
  instance:
    #lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    #lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}