server:
  port: 8084
spring:
  application:
    name: page-service
  devtools:
    restart:
      enabled: true  #设置开启热部署
  thymeleaf:  #thymeleaf做了缓存，我们应关掉
    cache: false
  rabbitmq:
    host: 192.168.153.129
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

